### ISSUE TITLE
Issue#1

### ISSUE THREAD

**Issue by Retroperspect** [HakimiX/UFO#1]
both as a heads up depending if you talked with helge or not we're suppose to report on the other groups issue tab on github so thats where we expect you to report your issues to us.
first issue about the blog, it's in danish.
we consist of 2 danish and one swede but it must be stressed that international communication is needed.

**Comment by HakimiX** [comment]
Hi 
Due to work we have not been able to look at your blog entry yet, but we will provide some feedback for your blog entry tonight. We thought you were a danish group, hence why the blog is written in danish, but if you'd like we can rewrite it in english? 

Best regards
Group K

**Comment by Retroperspect** [comment]
It's not really needed for most of us and it would require a lot of work rewriting the entire thing, it would be nice for Emmely as she's Swedish, but it was mostly a minor note about your communication front, but do please write your issues to us in english.

**Comment by HakimiX** [comment]
Okay. Are we allowed to incorporate your feedback immediately or do we have to wait after the presentation?

**Comment by Retroperspect** [comment]
I'm unsure actually, I think we have to wait until after the exam though if https://datsoftlyngby.github.io/soft2017fall/UFO_plan.html is to go by

**Comment by Retroperspect** [comment]
after reading more into it, it seems we're suppose to implement the feedback into our presentation as per 
The critiquing group is then asked to present (orally, but no slides) their critique, and whether they field it has been addressed properly.
I read field as feel as in whether they feel it has been addressed properly
my bad

**Comment by HakimiX** [comment]
Okay that makes more sense, otherwise, we would have been slaughtered at the presentation without implementing the feedback your group has provided :)
