### ISSUE TITLE
Confusion -

### ISSUE THREAD

**Issue by DanielHauge** [HakimiX/UFO#6]
Hi

What is the issue?:

- I was confused of what the issue/Problem or w/e you are proposing a solution for.
is it?
- The internet is riddled with unsecure servers which costs milions of [insert valuta here] a year.
or is it?:
- Nginx servers are generaly bad at security which costs users alot of development time and money.
£ Where's you want to propose a solution for this?

Lets imagine i personally wasn't using nginx but for example a tomcat server, and i was looking for something with secure servers. I would go straight past this entry, because it doesn't concern me, very narrow. But if refomulated, it could be relevant for me to. By talking about general security and not speecificly for nginx servers only.

**Why should i care? (Is this issue realy affecting me?):**

- Why is having unsecure nginx server bad for me?. What will it do?. (It is important for me to not think like this: "Meeh, probably nothing bad for me, maybe just need to restart server at some point because of DDoS attack or something, no biggie."

**What is your solution realy?:**  

- Have you accidently developed and researched the exact same solution as digital ocean? 
- Or is your solution to follow what digital ocean have found?

**What will this solution actully do for me?:**

- The solution will increase my security. Okay...... But what will i gain by that, hmm i don't know, maybe not worth it.

> I recommend to suggest(Emphasize) that by doing the solution, i will gain something: No more hackers which leads to less costs for maintenence, No more system chrashses which leads to better customer satisfaction. Or something like that.

Best
Daniel

**Comment by HakimiX** [comment]
Hi Daniel 

Thank you for the feedback. 

best regards

Group k

**Comment by HakimiX** [comment]
HI 

What was the name of the tool you mentioned for testing webserver security?

**Comment by DanielHauge** [comment]
Hi.

It is called Offensive Web testing framework (OWTF) and is build on Open
Web Application Security Project (OWASP)

https://www.owasp.org/index.php/OWASP_OWTF

Best
Daniel F. Hauge

2017-12-18 21:18 GMT+01:00 HakimiX <notifications@github.com>:

**Comment by HakimiX** [comment]
Thank you 👍
